<?xml version="1.0"?>
<package format="2">
  <name>fv_gripper_ctrl</name>
  <version>0.0.0</version>
  <description>Gripper control ROS node with FV</description>
  <author email="info@akihikoy.net">Akihiko Yamaguchi</author>
  <maintainer email="info@akihikoy.net">Akihiko Yamaguchi</maintainer>
  <license>Described in LICENSE</license>
  <url>http://akihikoy.net/p/fv</url>
  <buildtool_depend>catkin</buildtool_depend>

  <depend>rospy</depend>
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>
  <depend>tf</depend>
  <depend>ay_py</depend>
  <depend>ay_util</depend>
  <depend>fingervision_msgs</depend>

  <export>
  </export>
</package>
